Check for core support and only enable ssh for now (#3)

diff --git a/hooks/configure b/hooks/configure
--- a/hooks/configure
+++ b/hooks/configure
@@ -14,8 +14,14 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+# check if we have core support and exit cleanly if not
+if ! systemctl --version >/dev/null 2>&1; then
+    echo "Cannot run systemctl - is core-support available?"
+    exit 0
+fi
+
 # list of services we can disable and enable
-SERVICES="ssh rsyslog systemd-journald systemd-timesyncd"
+SERVICES="ssh"
 
 switch_handle_power_key() {
     dir="/etc/systemd/logind.conf.d"
